# Generated by Django 3.1.1 on 2020-10-03 10:53

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Action')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'db_table': 'action',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='company_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compname', models.CharField(max_length=10000, null=True, verbose_name='Company Name')),
                ('city', models.TextField(max_length=500, null=True, verbose_name='City')),
                ('draft', models.TextField(null=True, verbose_name='Draft')),
                ('budget', models.CharField(max_length=1000, null=True, verbose_name='Budget')),
                ('state', models.CharField(max_length=1000, null=True, verbose_name='State')),
                ('address', models.TextField(null=True, verbose_name='Address')),
                ('country', models.CharField(max_length=1000, null=True, verbose_name='Country')),
                ('website', models.CharField(max_length=1000, null=True, verbose_name='Website')),
                ('createddate', models.DateField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Company Master',
                'verbose_name_plural': 'Company Master',
                'db_table': 'company_master',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3000, verbose_name='Country Name')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'country_db',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='partner_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Partner Category Master',
                'verbose_name_plural': 'Partner Categories Master',
                'db_table': 'partner_master',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3000, verbose_name='Purpose')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.actions', verbose_name='Action')),
            ],
            options={
                'verbose_name': 'Purpose',
                'verbose_name_plural': 'Purpose',
                'db_table': 'purpose',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Status')),
                ('color', models.CharField(blank=True, default='gray', max_length=100, verbose_name='Set Background Color')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
                'db_table': 'status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='user_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'User Type',
                'verbose_name_plural': 'User Types',
                'db_table': 'user_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='user_zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'User Zone',
                'verbose_name_plural': 'User Zones',
                'db_table': 'user_zone',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, default='', upload_to=app.models.upload_user, verbose_name='Image')),
                ('name', models.CharField(max_length=1000, verbose_name='Full Name')),
                ('phoneno', models.CharField(blank=True, default='', max_length=20, verbose_name='Mobile Number')),
                ('username', models.CharField(max_length=200, verbose_name='Username')),
                ('password', models.CharField(max_length=1000, verbose_name='Password')),
                ('status', models.CharField(blank=True, default='active', max_length=20, null=True, verbose_name='Status')),
                ('usercreateDate', models.DateField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='admin_id', to=settings.AUTH_USER_MODEL, verbose_name='TL Name')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_type', verbose_name='Department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_zone', verbose_name='Zone')),
            ],
            options={
                'verbose_name': 'User Detail',
                'verbose_name_plural': 'User Details',
                'db_table': 'user_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='todays_remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name="Today's Remark")),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': "Today's Remark",
                'verbose_name_plural': "Today's Remarks",
                'db_table': 'todays_remark',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tblcalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft', models.CharField(max_length=3000, verbose_name='Draft')),
                ('proposal', models.CharField(max_length=1000, verbose_name='Preposal')),
                ('createDate', models.DateField(auto_now_add=True)),
                ('topspender', models.CharField(max_length=100, verbose_name='Topsender')),
                ('noofschools', models.CharField(blank=True, default='0', max_length=1000, verbose_name='Number of school')),
                ('proposal_type', models.CharField(blank=True, default='NA', max_length=100, verbose_name='Proposal Type')),
                ('proposal_amt', models.CharField(blank=True, default='NA', max_length=100, verbose_name='Proposal Amt.')),
                ('proposaldate', models.DateField(blank=True, null=True)),
                ('cmpid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company_master', verbose_name='Company')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Creator Info',
                'verbose_name_plural': 'Creators Info',
                'db_table': 'init_call',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tblcallevents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastCFID', models.CharField(max_length=1000, verbose_name='Last Id')),
                ('nextCFID', models.CharField(max_length=1000, verbose_name='New Id')),
                ('draft', models.CharField(max_length=30000, verbose_name='Draft')),
                ('event', models.CharField(blank=True, max_length=30000, verbose_name='Event')),
                ('remarks', models.TextField(verbose_name='Remark')),
                ('fwd_date', models.DateTimeField(blank=True, verbose_name='Forwarded Date')),
                ('actontaken', models.CharField(max_length=500, verbose_name='Action Taken')),
                ('nextaction', models.TextField(verbose_name='Next Action')),
                ('meeting_type', models.CharField(blank=True, default='NA', max_length=100, verbose_name='Meeting Type')),
                ('live_loaction', models.TextField(blank=True, default='NA', verbose_name='Live Location URL')),
                ('mom_received', models.TextField(blank=True, default='NA', verbose_name='MOM Received')),
                ('appointmentdatetime', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('updateddate', models.DateTimeField(auto_now_add=True, null=True)),
                ('actiontype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.actions', verbose_name='Action Type')),
                ('assignedto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_to', to=settings.AUTH_USER_MODEL, verbose_name='Assign To')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cid', to='app.tblcalls', verbose_name='Table Calls')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.purpose', verbose_name='Purpose')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.status', verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Call Event',
                'verbose_name_plural': 'Call Events',
                'db_table': 'tblcallevents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=3000, verbose_name='State')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'states',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='purpose',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.status', verbose_name='Purpose'),
        ),
        migrations.CreateModel(
            name='next_action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, verbose_name='Next Action')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.purpose', verbose_name='Purpose')),
            ],
            options={
                'verbose_name': 'Next Action',
                'verbose_name_plural': 'Next Actions',
                'db_table': 'next_action',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='company_master',
            name='partnerType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.partner_master', verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='company_contact_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactperson', models.CharField(max_length=2000, null=True, verbose_name='Contact Person')),
                ('emailid', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('draft', models.TextField(null=True, verbose_name='Draft')),
                ('phoneno', models.CharField(max_length=20, null=True, verbose_name='Mobile Number')),
                ('designation', models.CharField(max_length=500, null=True, verbose_name='Designation')),
                ('createddate', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('company', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_contact', to='app.company_master', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Company Contact Master',
                'verbose_name_plural': 'Company Contact Masters',
                'db_table': 'company_contact_master',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=10000, verbose_name='City')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.state', verbose_name='State')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'city',
                'managed': True,
            },
        ),
    ]
