# Generated by Django 3.1.1 on 2020-10-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(default='pending', max_length=11, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='company_id',
            field=models.CharField(max_length=11, verbose_name='Company id'),
        ),
    ]
