# Generated by Django 3.1.2 on 2020-10-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201005_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_contact_master',
            name='type',
            field=models.CharField(default='alternate', max_length=20, null=True, verbose_name='Type'),
        ),
    ]
