# Generated by Django 3.1.2 on 2020-11-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_company_contact_master_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcallevents',
            name='updation_type',
            field=models.TextField(blank=True, default='updated', null=True, verbose_name='Updation Type'),
        ),
    ]
